FROM theta-public-registry.cn-hangzhou.cr.aliyuncs.com/theta/mirobody-backend:latest

WORKDIR /app

COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade -r requirements.txt && \
    pip list

